POST http://localhost:4000/users
Content-Type:  application/json

{
   "username":"joyyyy" ,
   "email":"joyyyy@gmail.com",
   "password":"Password@1"    
}

###
POST http://localhost:4000/users
Content-Type:  application/json

{
   "username":"admin" ,
   "email":"admin@gmail.com",
   "password":"Password@1"
}

### 
//get all users
GET http://localhost:4000/users
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzYwNzUxLCJleHAiOjE2ODgxMjA3NTF9.DU2_BO6cM6qqSOQA3PxGJlVcLZtU5pYO6jeHYs7rjrg

###
//get user by id
GET http://localhost:4000/users/004a4795-8edb-41c3-b77e-f987f8b65f38
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzYwNzUxLCJleHAiOjE2ODgxMjA3NTF9.DU2_BO6cM6qqSOQA3PxGJlVcLZtU5pYO6jeHYs7rjrg

###
//get user by Email
GET http://localhost:4000/users/email/joy@gmail.com
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzYwNzUxLCJleHAiOjE2ODgxMjA3NTF9.DU2_BO6cM6qqSOQA3PxGJlVcLZtU5pYO6jeHYs7rjrg

###
//update Profile
PUT http://localhost:4000/users/update
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlY2U5ZTY4Ni1iNjJjLTQ1ZjAtYjg3NC0wMmMxZDkzNWE1MDYiLCJ1c2VybmFtZSI6ImFub3RoZXIiLCJlbWFpbCI6ImFub3RoZXJAZ21haWwuY29tIiwibG9jYXRpb24iOm51bGwsImFib3V0IjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTY4Nzk2MDE1MiwiZXhwIjoxNjg4MzIwMTUyfQ.i63RE-GWh2nLOlWREwQJXQTKlw6jU1mq9JglpNeBJPk

{
   "username":"joy" ,
   "email":"another@gmail.com",
    "location": "Nyeri",
    "about": "About meeeee :)"
}

###
//delete user
DELETE http://localhost:4000/users/bbce660f-c430-47a1-9adc-4ca204d5feb6
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMDRhNDc5NS04ZWRiLTQxYzMtYjc3ZS1mOTg3ZjhiNjVmMzgiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95QGdtYWlsLmNvbSIsImxvY2F0aW9uIjoiTnllcmkiLCJhYm91dCI6IkFib3V0IG1lZWVlZSA6KSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3MjYyNTE0LCJleHAiOjE2ODc2MjI1MTR9.sYO4A4Tuyi9CXjKSgs_pbuaShJTYylzwtrvvO_FErcE


//login user
###
POST http://localhost:4000/users/login
Content-Type:  application/json

{
   "email":"another@gmail.com",
   "password":"Another@23"    
}

//login admin
###
POST http://localhost:4000/users/login
Content-Type:  application/json

{
    "email":"admin@gmail.com",
   "password":"Password@1"  
}

//--------------------------------------------------------questions-------------------------
//uid in url
###
POST http://localhost:4000/questions
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2ZWM3ZGEyOC1kMDk3LTQwOTQtODhiMC0wMDY0MmNmOGNkZmMiLCJ1c2VybmFtZSI6ImFub3RoZXIiLCJlbWFpbCI6ImFub3RoZXJAZ21haWwuY29tIiwibG9jYXRpb24iOm51bGwsImFib3V0IjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTY4ODExMzYzMCwiZXhwIjoxNjg4NDczNjMwfQ.tzpJMbtF0rPAYVeoa5D3rFyxNmXrQA6gS2Mc8uX0PfU

{
    "title":"questionnnn I am testinggggg", 
   "body":"a whooooolle" ,
   "tags":["one","two"]
   
   }

//get all questions
###
GET http://localhost:4000/questions/1
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzYwNzUxLCJleHAiOjE2ODgxMjA3NTF9.DU2_BO6cM6qqSOQA3PxGJlVcLZtU5pYO6jeHYs7rjrg


###
GET http://localhost:4000/questions/search/ok
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzYwNzUxLCJleHAiOjE2ODgxMjA3NTF9.DU2_BO6cM6qqSOQA3PxGJlVcLZtU5pYO6jeHYs7rjrg

//get questions by one User 
###
GET http://localhost:4000/questions/user/188b2253-ad41-4cd2-9392-45e183857fab
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzYwNzUxLCJleHAiOjE2ODgxMjA3NTF9.DU2_BO6cM6qqSOQA3PxGJlVcLZtU5pYO6jeHYs7rjrg


###
GET http://localhost:4000/questions/user
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzYwNzUxLCJleHAiOjE2ODgxMjA3NTF9.DU2_BO6cM6qqSOQA3PxGJlVcLZtU5pYO6jeHYs7rjrg
//get one question
###
GET http://localhost:4000/questions/question/7f8adc71-dcae-4a31-9b62-28594df9749a
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMDA3ODRhZC0zZDQyLTQxMDQtYmRiNi0yNjc1NjlhZGM0NTAiLCJ1c2VybmFtZSI6ImpveW1hcnkiLCJlbWFpbCI6ImpveW1hcjg5NjJAZ21haWwuY29tIiwibG9jYXRpb24iOm51bGwsImFib3V0IjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM4MDU1OSwiZXhwIjoxNjg3NzQwNTU5fQ.QgNrI_HDgE_WHzgMfOfI54JV93XACd8C0MSnw36NzP0



//delete question
###
DELETE http://localhost:4000/questions/delete/255e7a74-8909-4e23-ab48-1e3591cf1e61
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIzN2RiY2I1ZC0wMzU2LTRjZTQtOTdkMy0zODdkMDQzNzVlMTUiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4ODExNDQwMiwiZXhwIjoxNjg4NDc0NDAyfQ.q-A5GEW0UhymyQuj6N_oP2sG3mf-3PxwT4IBJ4fd-vI


//update question
###
PUT http://localhost:4000/questions/question/551e5dbe-feab-4ced-b8a0-29331ce6c500
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMDA3ODRhZC0zZDQyLTQxMDQtYmRiNi0yNjc1NjlhZGM0NTAiLCJ1c2VybmFtZSI6ImpveW1hcnkiLCJlbWFpbCI6ImpveW1hcjg5NjJAZ21haWwuY29tIiwibG9jYXRpb24iOm51bGwsImFib3V0IjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM4MDU1OSwiZXhwIjoxNjg3NzQwNTU5fQ.QgNrI_HDgE_WHzgMfOfI54JV93XACd8C0MSnw36NzP0

{
    "title":"update the question", 
   "body":"a whooooolle update" ,
   "tags":["one","two"]
   
   }

//get questions by tags 
###
GET http://localhost:4000/questions/tag/gcf
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NzYwNzUxLCJleHAiOjE2ODgxMjA3NTF9.DU2_BO6cM6qqSOQA3PxGJlVcLZtU5pYO6jeHYs7rjrg

   //------------------------answers----------------------
//qid in url
####
POST http://localhost:4000/answers/7c6db977-2880-435c-8e9f-1094ea848720
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NjkwMTY5LCJleHAiOjE2ODgwNTAxNjl9.u57Ru9R0SRx7UjiXqnJ39a8O6LWJ51I6fEzgQzBufBQ

{
    "answer": "my answer's answer"   
   }

//get answers of a question 
####
GET http://localhost:4000/answers/8ad08c75-d148-4d2a-b8ef-e24047a93953
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlY2U5ZTY4Ni1iNjJjLTQ1ZjAtYjg3NC0wMmMxZDkzNWE1MDYiLCJ1c2VybmFtZSI6ImpveV9tYXJ5IiwiZW1haWwiOiJhbm90aGVyQGdtYWlsLmNvbSIsImxvY2F0aW9uIjoiTnllcmkiLCJhYm91dCI6IkFib3V0IG1lZWVlZSA6KSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg4MDY4NDg3LCJleHAiOjE2ODg0Mjg0ODd9.VezKCoOxcdOehw--KJiDma6Qr-dLTuwZ7oX0MUoTZYE

###
GET http://localhost:4000/answers/answer/4c090764-8754-4b72-a311-ec837969a42d
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlY2U5ZTY4Ni1iNjJjLTQ1ZjAtYjg3NC0wMmMxZDkzNWE1MDYiLCJ1c2VybmFtZSI6ImpveV9tYXJ5IiwiZW1haWwiOiJhbm90aGVyQGdtYWlsLmNvbSIsImxvY2F0aW9uIjoiTnllcmkiLCJhYm91dCI6IkFib3V0IG1lZWVlZSA6KSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg4MDY4NDg3LCJleHAiOjE2ODg0Mjg0ODd9.VezKCoOxcdOehw--KJiDma6Qr-dLTuwZ7oX0MUoTZYE
//aid in url
####
POST http://localhost:4000/answers/prefer/ff23d7d8-478c-4113-859f-ca3917c7eaf5
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMDRhNDc5NS04ZWRiLTQxYzMtYjc3ZS1mOTg3ZjhiNjVmMzgiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95QGdtYWlsLmNvbSIsImxvY2F0aW9uIjoiTnllcmkiLCJhYm91dCI6IkFib3V0IG1lZWVlZSA6KSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NTA0MDEyLCJleHAiOjE2ODc4NjQwMTJ9.MERf2NL0OSSrZek7Ae-TwA_oHWS8XacP45Nehldqlts



//-------------comments--------
//aid in url
####
POST http://localhost:4000/comments/bc506573-f82d-4969-9cdf-2b9e343956fa
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NjkwMTY5LCJleHAiOjE2ODgwNTAxNjl9.u57Ru9R0SRx7UjiXqnJ39a8O6LWJ51I6fEzgQzBufBQ

{
    "comment": "the comment for my answer"
   
   }


//aid in url
####
GET http://localhost:4000/comments/8376df2f-e89d-4e89-8ab3-2a7e6b24ef71
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3NjkwMTY5LCJleHAiOjE2ODgwNTAxNjl9.u57Ru9R0SRx7UjiXqnJ39a8O6LWJ51I6fEzgQzBufBQ


//---------------------------votes-----------------
//aid in url
####
POST http://localhost:4000/votes/upvote/4c090764-8754-4b72-a311-ec837969a42d
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1YTg5ODU1Zi0xNWExLTQwMDctYTRiYi1kNDFkOTQ5NjkzMWUiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95bWFyeUBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3ODkyNDY1LCJleHAiOjE2ODgyNTI0NjV9.OU5VH8kzTbLcIbK5IF8KsSte1ORHEuqSO_vCKtqO-Jg
Content-Type:  application/json


//aid in url
####
POST http://localhost:4000/votes/downvote/ff23d7d8-478c-4113-859f-ca3917c7eaf5
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI0MzRiYmZkMy02ZmRkLTQ5ODYtODkxMy03MzI0N2VlMTIzNDciLCJ1c2VybmFtZSI6ImpveW1hcnkiLCJlbWFpbCI6ImpveW1hcjJAZ21haWwuY29tIiwibG9jYXRpb24iOm51bGwsImFib3V0IjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzMzNTEyOSwiZXhwIjoxNjg3Njk1MTI5fQ.PmjOPavUcQuyEnYZSqHibvef1UslLDvWhNXriLLUYg8


###
GET http://localhost:4000/tags
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI0MzRiYmZkMy02ZmRkLTQ5ODYtODkxMy03MzI0N2VlMTIzNDciLCJ1c2VybmFtZSI6ImpveW1hcnkiLCJlbWFpbCI6ImpveW1hcjJAZ21haWwuY29tIiwibG9jYXRpb24iOm51bGwsImFib3V0IjpudWxsLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzMzNTEyOSwiZXhwIjoxNjg3Njk1MTI5fQ.PmjOPavUcQuyEnYZSqHibvef1UslLDvWhNXriLLUYg8
