POST http://localhost:4000/users
Content-Type:  application/json

{
   "username":"joymary" ,
   "email":"joymary@gmail.com",
   "password":"Password@1"    
}

###
POST http://localhost:4000/users
Content-Type:  application/json

{
   "username":"admin" ,
   "email":"admin@gmail.com",
   "password":"Password@1"
}

### 
//get all users
GET http://localhost:4000/users
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1NzUwMWI1Ny05MTllLTQ0MDItYTJkYi1kYmJhMDJlZTY3M2QiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4Njk5OTAyOCwiZXhwIjoxNjg3MzU5MDI4fQ.V3rcIeP0QzjyaG5bgp4q9LvTK3hOPte2TW-jX0WpZK8

###
//get user by id
GET http://localhost:4000/users/bbce660f-c430-47a1-9adc-4ca204d5feb6
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1NzUwMWI1Ny05MTllLTQ0MDItYTJkYi1kYmJhMDJlZTY3M2QiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4Njk5OTAyOCwiZXhwIjoxNjg3MzU5MDI4fQ.V3rcIeP0QzjyaG5bgp4q9LvTK3hOPte2TW-jX0WpZK8

###
//get user by Email
GET http://localhost:4000/users/email/joy@gmail.com
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1NzUwMWI1Ny05MTllLTQ0MDItYTJkYi1kYmJhMDJlZTY3M2QiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4Njk5OTAyOCwiZXhwIjoxNjg3MzU5MDI4fQ.V3rcIeP0QzjyaG5bgp4q9LvTK3hOPte2TW-jX0WpZK8

###
//update Profile
PUT http://localhost:4000/users/004a4795-8edb-41c3-b77e-f987f8b65f38
Content-Type:  application/json

{
   "username":"joy" ,
   "email":"joy@gmail.com",
    "location": "Nyeri",
    "about": "About meeeee :)"
}

###
//delete user
DELETE http://localhost:4000/users/bbce660f-c430-47a1-9adc-4ca204d5feb6
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1NzUwMWI1Ny05MTllLTQ0MDItYTJkYi1kYmJhMDJlZTY3M2QiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4Njk5OTAyOCwiZXhwIjoxNjg3MzU5MDI4fQ.V3rcIeP0QzjyaG5bgp4q9LvTK3hOPte2TW-jX0WpZK8


//login user
###
POST http://localhost:4000/users/login
Content-Type:  application/json

{
   "email":"joy@gmail.com",
   "password":"Password@1"    
}

//login admin
###
POST http://localhost:4000/users/login
Content-Type:  application/json

{
    "email":"admin@gmail.com",
   "password":"Password@1"  
}

//--------------------------------------------------------questions-------------------------
###
POST http://localhost:4000/questions/004a4795-8edb-41c3-b77e-f987f8b65f38
Content-Type:  application/json


{
    "title":"questionnnn", 
   "body":"a whooooolle" ,
   "tags":[{"tid":"t1","tagname":"name"},{"tid":"t2","tagname":"name"}]
   
   }

//get all questions
###
GET http://localhost:4000/questions

//get questions by one User 
###
GET http://localhost:4000/questions/004a4795-8edb-41c3-b77e-f987f8b65f38

//get one question
###
GET http://localhost:4000/questions/question/551e5dbe-feab-4ced-b8a0-29331ce6c500



//delete question
###
DELETE http://localhost:4000/questions/delete/f17a5456-8d04-482f-a886-872ea31a1753
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1NzUwMWI1Ny05MTllLTQ0MDItYTJkYi1kYmJhMDJlZTY3M2QiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJsb2NhdGlvbiI6bnVsbCwiYWJvdXQiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4Njk5OTAyOCwiZXhwIjoxNjg3MzU5MDI4fQ.V3rcIeP0QzjyaG5bgp4q9LvTK3hOPte2TW-jX0WpZK8


//update question
###
PUT http://localhost:4000/questions/question/551e5dbe-feab-4ced-b8a0-29331ce6c500/004a4795-8edb-41c3-b77e-f987f8b65f38
Content-Type:  application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMDRhNDc5NS04ZWRiLTQxYzMtYjc3ZS1mOTg3ZjhiNjVmMzgiLCJ1c2VybmFtZSI6ImpveSIsImVtYWlsIjoiam95QGdtYWlsLmNvbSIsImxvY2F0aW9uIjoiTnllcmkiLCJhYm91dCI6IkFib3V0IG1lZWVlZSA6KSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3MDExOTc3LCJleHAiOjE2ODczNzE5Nzd9.acb6MtZ5Y0atGuUULS9C0amd3Y6RFu7GRiH7sfrlX1A

{
    "title":"update the question", 
   "body":"a whooooolle update" ,
   "tags":[{"tid":"t2","tagname":"name"}]
   
   }


   //------------------------answers----------------------
//qid in url
####
POST http://localhost:4000/answers/5
Content-Type:  application/json

{
    "answer": "the looong answer pt 2 ",
    "uid":"004a4795-8edb-41c3-b77e-f987f8b65f38"
   
   }

//get answers of a question 
####
GET http://localhost:4000/answers/551e5dbe-feab-4ced-b8a0-29331ce6c500


//aid in url
####
POST http://localhost:4000/answers/prefer/c0e2b4d2-3e49-452b-a234-935b454ab2a0
Content-Type:  application/json

{
    "qid":"551e5dbe-feab-4ced-b8a0-29331ce6c500" 
   }



//---------comments--------
